version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
#            - cci-pcotesthaskell-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-scottytest-{{ checksum "stack.yaml" }}			
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
#      - run:
#          name: Run tests
#          command: stack --no-terminal test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: cci-scottytest-{{ checksum "stack.yaml" }}
#          key: cci-scottytest-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
      - store_artifacts: # upload build artifact for display in CircleCi
          path: ~/.local/bin/scottytest-exe
          destination: scottytest-exe